input: "RNA-seq-sample-data"
output: "outputs"
samples: Collibri_standard_protocol-HBR-Collibri-100_ng-2_S1 Collibri_standard_protocol-HBR-Collibri-100_ng-3_S2 Collibri_standard_protocol-UHRR-Collibri-100_ng-2_S3 Collibri_standard_protocol-UHRR-Collibri-100_ng-3_S4 KAPA_mRNA_HyperPrep_-HBR-KAPA-100_ng_total_RNA-2_S5 KAPA_mRNA_HyperPrep_-HBR-KAPA-100_ng_total_RNA-3_S6 KAPA_mRNA_HyperPrep_-UHRR-KAPA-100_ng_total_RNA-2_S7 KAPA_mRNA_HyperPrep_-UHRR-KAPA-100_ng_total_RNA-3_S8
adapters: "adapters.fa"
